# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    environment: docker_hub

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
    - name: Build Docker Image
      run: docker build -t gabriellft/laffitteassignment:${{ github.sha }} .

    - name: Tag Image as Latest
      run: docker tag gabriellft/laffitteassignment:${{ github.sha }} gabriellft/laffitteassignment:latest

    - name: Push Docker Image to Registry
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
        docker push gabriellft/laffitteassignment:${{ github.sha }}
        docker push gabriellft/laffitteassignment:latest


